sudo: false
notifications:
  email: false
language: python
python:
  - "2.7"
branches:
  only:
  - master
before_install:
  - pip install coverage
  - pip install coveralls
install:
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - coverage run --source=asymmetry tests/test_get_edge_weights.py
after_success:
  - coveralls
