#!/usr/bin/env python
import argparse
from asymmetry.fslx import DEFAULTS, fslxmean


parser = argparse.ArgumentParser(description='Take the mean of multiple images.')

parser.add_argument('images', help='images to take the mean of', nargs='+')
parser.add_argument('output', help='output image path', type=str)
parser.add_argument('-m', '--mask', help='image used to mask the mean image',
                    action='store_true')

args = parser.parse_args()
if args.mask:
    fslxmean(args.images, args.output, mask=args.mask)
else:
    fslxmean(args.images, args.output, mask=DEFAULTS['mask'])
